# AI Pipeline Automation Configuration  
api:
  base_url: "http://localhost:3002"
  company_email: "admin@clann.ai"
  company_password: "demo123"

pipeline:
  data_directory: "data"
  processed_games_file: "processed_games.json"
  
game_mapping:
  # Green Island VEO match
  "19-20250419": "ed4150c5-9d60-4647-a568-6d1da24a9765"

settings:
  monitoring_interval: 30
  max_retries: 3
  log_level: "INFO"
